// Big query matrix. Keep it diverse: vary specialty × form-type × source.
const specialties = {
  'family-medicine': ['family medicine','primary care'],
  'internal-medicine': ['internal medicine'],
  'pediatrics': ['pediatric','pediatrician'],
  'geriatrics': ['geriatric','older adult'],
  'psychiatry': ['psychiatry','behavioral health'],
  'psychology': ['psychology','therapist'],
  'addiction-medicine': ['addiction','substance use'],
  'orthopedics': ['orthopedic','orthopaedic'],
  'neurosurgery': ['neurosurgery'],
  'ent': ['ENT','otolaryngology'],
  'plastic-surgery': ['plastic surgery','cosmetic'],
  'bariatric': ['bariatric','weight loss surgery'],
  'obgyn': ['obstetrics gynecology','OB/GYN','gynecology'],
  'fertility': ['fertility','reproductive endocrinology'],
  'midwifery': ['midwife','midwifery'],
  'dev-behavioral-peds': ['developmental behavioral pediatrics','autism evaluation','ADHD'],
  'cardiology': ['cardiology'],
  'pulmonology': ['pulmonology','pulmonary'],
  'gastroenterology': ['gastroenterology'],
  'endocrinology': ['endocrinology','diabetes'],
  'rheumatology': ['rheumatology'],
  'nephrology': ['nephrology'],
  'neurology': ['neurology'],
  'allergy-immunology': ['allergy immunology','allergist'],
  'oncology': ['oncology','cancer center'],
  'infectious-disease': ['infectious disease','HIV clinic'],
  'dermatology': ['dermatology'],
  'ophthalmology': ['ophthalmology'],
  'optometry': ['optometry'],
  'dental': ['dental','dentist'],
  'orthodontics': ['orthodontic','orthodontist'],
  'physical-therapy': ['physical therapy','physiotherapy'],
  'occupational-therapy': ['occupational therapy'],
  'speech-language': ['speech language pathology','SLP'],
  'chiropractic': ['chiropractic'],
  'acupuncture': ['acupuncture','Chinese medicine'],
  'naturopathy': ['naturopathic'],
  'functional-medicine': ['functional medicine'],
  'massage': ['massage therapy'],
  'pain-management': ['pain management','pain clinic'],
  'sleep-medicine': ['sleep medicine','sleep clinic'],
  'palliative-hospice': ['palliative care','hospice'],
  'sports-medicine': ['sports medicine'],
  'travel-medicine': ['travel medicine','travel clinic'],
  'occupational-medicine': ['occupational medicine'],
  'transgender-care': ['gender affirming','transgender health'],
  'urology': ['urology'],
  'audiology': ['audiology','hearing'],
  'veterinary': ['veterinary','small animal'],
};

const formTemplates = (specTerm) => ([
  { hint: 'new-patient-intake',   q: `"new patient intake form" filetype:pdf ${specTerm}` },
  { hint: 'new-patient-intake',   q: `"new patient packet" filetype:pdf ${specTerm}` },
  { hint: 'history-ros',          q: `"medical history" "review of systems" filetype:pdf ${specTerm}` },
  { hint: 'preprocedure',         q: `"pre-operative questionnaire" filetype:pdf ${specTerm}` },
  { hint: 'followup',             q: `"follow up questionnaire" filetype:pdf ${specTerm}` },
  { hint: 'telehealth-eintake',   q: `"new patient" intake form ${specTerm} site:jotform.com OR site:intakeq.com OR site:simplepractice.com` },
]);

// PROM scales as specialty=condition for follow-up gold
const proms = [
  ['mental-health-depression','PHQ-9 patient health questionnaire'],
  ['mental-health-anxiety','GAD-7 generalized anxiety'],
  ['mental-health-substance','AUDIT-C alcohol use'],
  ['mental-health-substance','DAST-10 drug abuse screening'],
  ['mental-health-bipolar','MDQ mood disorder questionnaire'],
  ['peds-adhd','Vanderbilt ADHD assessment'],
  ['peds-autism','M-CHAT-R toddler autism'],
  ['peds-anxiety','SCARED child anxiety related disorders'],
  ['ortho-spine','Oswestry Disability Index'],
  ['ortho-spine','Neck Disability Index'],
  ['ortho-spine','Roland Morris disability'],
  ['ortho-upperlimb','QuickDASH upper extremity'],
  ['ortho-knee','KOOS knee outcome'],
  ['ortho-hip','HOOS hip outcome'],
  ['ortho-knee','WOMAC osteoarthritis'],
  ['ortho-foot','FAAM foot ankle ability'],
  ['urology','IPSS international prostate symptom score'],
  ['urology','OABSS overactive bladder'],
  ['urology','SHIM IIEF-5 erectile function'],
  ['gyn','FSFI female sexual function index'],
  ['rheumatology','HAQ-DI health assessment questionnaire'],
  ['rheumatology','RAPID3 rheumatoid arthritis'],
  ['rheumatology','BASDAI ankylosing spondylitis'],
  ['rheumatology','ASAS-HI axial spondyloarthritis'],
  ['rheumatology','PsAID psoriatic arthritis impact'],
  ['rheumatology','FIQR fibromyalgia revised'],
  ['pain','Brief Pain Inventory BPI'],
  ['pain','McGill Pain Questionnaire'],
  ['pulmonology','mMRC dyspnea scale'],
  ['pulmonology','COPD Assessment Test CAT'],
  ['pulmonology','Asthma Control Test ACT'],
  ['gastroenterology','IBDQ inflammatory bowel disease questionnaire'],
  ['gastroenterology','IBS-SSS irritable bowel severity'],
  ['gastroenterology','Rome IV diagnostic questionnaire'],
  ['gastroenterology','Bristol stool chart'],
  ['sleep','Epworth Sleepiness Scale'],
  ['sleep','Insomnia Severity Index ISI'],
  ['sleep','STOP-BANG obstructive sleep apnea'],
  ['sleep','Berlin questionnaire sleep apnea'],
  ['neurology','MoCA Montreal Cognitive Assessment'],
  ['neurology','MMSE mini mental state'],
  ['geriatrics','Barthel index ADL'],
  ['geriatrics','Lawton instrumental activities daily living'],
  ['oncology','EORTC QLQ-C30 quality of life'],
  ['oncology','FACT-G functional assessment cancer'],
  ['oncology','EPIC-26 prostate cancer'],
  ['oncology','Edmonton Symptom Assessment ESAS'],
  ['general-prom','PROMIS-29 profile'],
  ['general-prom','EQ-5D-5L health questionnaire'],
  ['general-prom','SF-36 short form health survey'],
];

const list = [];
for (const [spec, terms] of Object.entries(specialties)) {
  for (const t of terms) for (const tpl of formTemplates(t)) {
    list.push({ specialty: spec, formTypeHint: tpl.hint, q: tpl.q });
  }
}
for (const [spec, scale] of proms) {
  list.push({ specialty: spec, formTypeHint: 'validated-prom', q: `"${scale}" filetype:pdf` });
  list.push({ specialty: spec, formTypeHint: 'validated-prom', q: `${scale} filetype:pdf site:.edu OR site:.gov OR site:.org` });
}

process.stdout.write(JSON.stringify(list));
